name: Run ASIM testers on "eco-connector-test" workspace
on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize, labeled]
    paths:
    - 'Parsers/ASimDns/Parsers/**'
    - 'Parsers/ASimNetworkSession/Parsers/**'
    - 'Parsers/ASimWebSession/Parsers/**'
    - 'Parsers/ASimProcessEvent/Parsers/**'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
      id-token: write
      contents: read

jobs: 
  Windows-latest:
      runs-on: windows-latest
      steps:
        - name: Checkout repo        
          uses: actions/checkout@v2
        - name: Login to Azure Public Cloud with AzPowershell
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
            enable-AzPSSession: true
        - name: Run Asim testers
          uses: azure/powershell@v1
          with:
             inlineScript: |
              & ".script/tests/asimParsersTest/runAsimTesters.ps1"
             azPSVersion: "latest"
             errorActionPreference : continue
             failOnStandardError: false
