name: Run Azure Login with OpenID Connect and PowerShell
on:
  pull_request:
    types: [opened, edited, reopened, synchronize, labeled]

permissions:
      id-token: write
      contents: read
      
jobs: 
  Windows-latest:
      runs-on: windows-latest
      steps:
        - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
            enable-AzPSSession: true

        - name: 'Get resource group with PowerShell action'
          uses: azure/powershell@v1
          with:
             inlineScript: |
              $x = Get-ChildItem -Path .
              echo "Get-ChildItem -Path ."
              echo $x
              $y = Get-ChildItem -Path ..
              echo "Get-ChildItem -Path .."
              echo $y
              $z = Get-ChildItem -Path ".script/tests/asimTest"
              echo "Get-ChildItem -Path .script/tests/asimTest"
              echo $z
              $a = Get-ChildItem -Path "./.script/tests/asimTest"
              echo "Get-ChildItem -Path ./.script/tests/asimTest"
              echo $a
              & ".script/tests/asimTest/convertYamlToLetStatements.ps1"
             azPSVersion: "latest"