name: Run ASIM testers on "eco-connector-test" workspace
on:
  pull_request:
    types: [opened, edited, reopened, synchronize, labeled]

permissions:
      id-token: write
      contents: read
      
jobs: 
  runAsimTesters:
      runs-on: windows-latest
      steps:
        - name: Checkout repo        
          uses: actions/checkout@v2
        - name: Login to Azure Public Cloud with AzPowershell
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
            enable-AzPSSession: true
        - name: Run Asim testers
          uses: azure/powershell@v1
          with:
             inlineScript: |
              & ".script/tests/asimParsersTest/runAsimTesters.ps1"
             azPSVersion: "latest"
             errorActionPreference : continue
             failOnStandardError: false